<a href="https://colab.research.google.com/github/Tushika2024/computer_vision_course/blob/main/computer_vision_freecodecamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSORS - MULTIDIMENSIONAL ARRAYS

In [2]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d=tf.constant([2,0,-3,8.],)
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8.], shape=(4,), dtype=float32)


In [5]:
tensor_two_d=tf.constant([[1,2,0],
                          [3,5,-1],
                           [1,5,6],
                          [2,3,8]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [6]:
tensor_three_d=tf.constant([
  [[1,2,0],
  [3,5,-1]],
  [[1,2,0],
  [3,5,-1]]
  ])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[ 1  2  0]
  [ 3  5 -1]]], shape=(2, 2, 3), dtype=int32)


In [7]:
tensor_three_d.ndim

3

In [8]:
tensor_four_d=tf.constant([[
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
],
[
    [
        [1,2,3],
         [4,5,6]
    ],
     [
         [10,11,2],
         [90,100,20]
     ]
]])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   3]
   [  4   5   6]]

  [[  7   8   9]
   [ 10  11  12]]]


 [[[  1   2   3]
   [  4   5   6]]

  [[ 10  11   2]
   [ 90 100  20]]]], shape=(2, 2, 2, 3), dtype=int32)


In [9]:
#cast operation
tensor_one_d=tf.constant([2,3,4.,0],dtype=tf.float32)
tenor_casted=tf.cast(tensor_one_d,dtype=tf.bool)
print(tenor_casted)
print(tensor_one_d)


tf.Tensor([ True  True  True False], shape=(4,), dtype=bool)
tf.Tensor([2. 3. 4. 0.], shape=(4,), dtype=float32)


In [10]:
tensor_string=tf.constant(["hello wworld","hi"])
print(tensor_string)

tf.Tensor([b'hello wworld' b'hi'], shape=(2,), dtype=string)


In [11]:
import numpy as np


In [12]:
np_array=np.array([1,2,4])
print(np_array)

convert_to_tensor=tf.convert_to_tensor(np_array)
print(convert_to_tensor)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [13]:
#identity matrix
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    dtype=tf.bool,
    name=None
)
print(eye_tensor)



tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [14]:
#identity matrix
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=3,
    dtype=tf.int32,  ##2*4*5*3
    batch_shape=[2,4],
    name=None
)
print(eye_tensor)



tf.Tensor(
[[[[1 0 0]
   [0 1 0]
   [0 0 1]
   [0 0 0]
   [0 0 0]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]
   [0 0 0]
   [0 0 0]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]
   [0 0 0]
   [0 0 0]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]
   [0 0 0]
   [0 0 0]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]
   [0 0 0]
   [0 0 0]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]
   [0 0 0]
   [0 0 0]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]
   [0 0 0]
   [0 0 0]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]
   [0 0 0]
   [0 0 0]]]], shape=(2, 4, 5, 3), dtype=int32)


In [15]:
#fill method => to  create tensor with a scalar value
fill_tensor=tf.fill(
    [3,4],
    value=5,
    name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [16]:
#ones method => scalar value=1
ones_tensor=tf.ones(
    [3,4],
    dtype=tf.int32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [17]:
#ones like =>create a tensor of all ones that has thee same shape as the input
ones_like_tensor=tf.ones_like(
    input=[1,2,3],
    dtype=tf.float32,
    name=None
)
print(ones_like_tensor)

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


In [18]:
#zeros method => scalar value=0
zeros_tensor=tf.zeros(
    shape=[3,4],
    dtype=tf.int32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [19]:
#zeros like same as ones like (scalar value=0)

In [20]:
#shape method=> return the tensor contaning the shape pf the input tensor
shape_tensor=tf.shape(zeros_tensor)
print(shape_tensor)

print(zeros_tensor.shape)  # tuple


tf.Tensor([3 4], shape=(2,), dtype=int32)
(3, 4)


In [21]:
#rank  method
rank_tensor=tf.rank(zeros_tensor)
print(rank_tensor)

tf.Tensor(2, shape=(), dtype=int32)


In [22]:
#size method =>no of elements in tensor
size_tensor=tf.size(zeros_tensor)
print(size_tensor)
#

tf.Tensor(12, shape=(), dtype=int32)


TENSOR INTIALISATION

In [23]:
#tensors creation from normal distribution
random_tensor=tf.random.normal(
    shape=(3,4),
    mean=90.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[88.26176  90.194305 89.94295  91.289444]
 [90.381355 90.18026  88.626595 90.20734 ]
 [91.55069  89.81823  90.669266 88.98007 ]], shape=(3, 4), dtype=float32)


In [24]:
#tnsors from uniform dist
random_tensor=tf.random.uniform(
    shape=(3,4),
    minval=18,
    maxval=90, ## bydefault maxval is 1
    dtype=tf.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[83.71848  62.366516 22.805506 18.405172]
 [81.69148  22.936707 54.72805  56.498985]
 [39.37529  68.16035  22.06331  35.04848 ]], shape=(3, 4), dtype=float32)


In [29]:
tf.range(2,10)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

TENSOR INDEXING

In [33]:
tensor_new=tf.constant([1,2,3,4,5,6]) ##0 till n
print(tensor_new)
print(tensor_new[0:3]) ## min:max-1
print(tensor_new[:3])
print(tensor_new[0:])
print(tensor_new[0:-3]) # n-1=-1

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [41]:
tensor_two_d=tf.constant([[1,2,0],
                          [3,5,-1],
                           [1,5,6],
                          [2,3,8]])
print(tensor_two_d)
print(tensor_two_d[0:3,1:3])  ## row(min:max+1),col(min:max+1)
print(tensor_two_d[0:3,:])
print(tensor_two_d[2,:])
print(tensor_two_d[2,0])
print(tensor_two_d[...,1]) ##...=>complete row

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 2  0]
 [ 5 -1]
 [ 5  6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)
tf.Tensor([1 5 6], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [43]:
tensor_three_d=tf.constant([
  [[1,2,0],
  [3,5,-1]],
  [[1,2,0],
  [3,5,-1]]
  ])
print(tensor_three_d)
print(tensor_three_d[0 , : , :])

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[ 1  2  0]
  [ 3  5 -1]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


MATHS OPERATIONS

In [50]:
#tf.math
#abs
x_abs=tf.constant([-10,-10,30])
tf.math.abs(x_abs)
tf.abs(x_abs)

x_abs_comples=tf.constant([-2.1+0.7j])
print(tf.abs(x_abs_comples))  ##root of a*a+b*b

tf.Tensor([2.21359436], shape=(1,), dtype=float64)


In [57]:
#add  , subtract , multiply, divide (elementwise) of same shape bith tensors
x_1=tf.constant([1,2,3])
x_2=tf.constant([4,5,6])
print(tf.add(x_1,x_2))
print(tf.math.add(x_1,x_2))
print(tf.math.subtract(x_1,x_2))
print(tf.math.multiply(x_1,x_2))
print(tf.math.divide(x_1,x_2))

#divide_no_nan of same shape
x_1=tf.constant([1,2,3])
x_2=tf.constant([0,2,3])
print(tf.math.divide_no_nan(x_1,x_2))
print(tf.math.divide(x_1,x_2))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor([0. 1. 1.], shape=(3,), dtype=float64)
tf.Tensor([inf  1.  1.], shape=(3,), dtype=float64)


In [58]:
#add  , subtract , multiply, divide (elementwise) of diff shape tensors
x_1=tf.constant([1,2,3])
x_2=tf.constant([4])
print(tf.add(x_1,x_2))        ###====== BROADCASTING X_2 STRECHED TO SAME DIMENSION AS OF X_1=====
print(tf.math.add(x_1,x_2))
print(tf.math.subtract(x_1,x_2))
print(tf.math.multiply(x_1,x_2))
print(tf.math.divide(x_1,x_2))

#divide_no_nan of same shape
x_1=tf.constant([1,2,3])
x_2=tf.constant([0])
print(tf.math.divide_no_nan(x_1,x_2))
print(tf.math.divide(x_1,x_2))

tf.Tensor([5 6 7], shape=(3,), dtype=int32)
tf.Tensor([5 6 7], shape=(3,), dtype=int32)
tf.Tensor([-3 -2 -1], shape=(3,), dtype=int32)
tf.Tensor([ 4  8 12], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.5  0.75], shape=(3,), dtype=float64)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float64)
tf.Tensor([inf inf inf], shape=(3,), dtype=float64)


In [61]:
# BROADCASTING ANOTHER EG
x1=tf.constant([5,3,6,6,4,6])
x2=tf.constant([[7],[5],[3]])
print(x1.shape)
print(x2.shape)
print(tf.math.multiply(x1,x2))

(6,)
(3, 1)
tf.Tensor(
[[35 21 42 42 28 42]
 [25 15 30 30 20 30]
 [15  9 18 18 12 18]], shape=(3, 6), dtype=int32)


In [64]:
#argmax  => gives index of max element
x_argmax=tf.constant([10,20,30,40])
print(tf.math.argmax(x_argmax))


multidim=tf.constant([   # for multidim tensor needs to fix the axis
    [2,20,30,3,6],
    [3,11,16,1,8],
    [144,45,23,5,27]
])
print(tf.math.argmax(multidim,0))   # fix rows(0) comparison along col1
print(tf.math.argmax(multidim,1))

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 0], shape=(3,), dtype=int64)


In [65]:
#pow
x1= tf.constant([[2,2],[3,3]])
x2=tf.constant([[1,2],[3,4]])
print(tf.math.pow(x1,x2))

tf.Tensor(
[[ 2  4]
 [27 81]], shape=(2, 2), dtype=int32)
